baseURL = "https://jyamauchi780.github.io/asltym-hp/"
title = "ASL Toyama"
theme = "paige"

defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false

[params.paige.site]
disable_breadcrumbs = true

[params.paige.pages]
disable_reading_time = true
disable_word_count = true
disable_toc = true

[markup.goldmark.parser.attribute]
block = true
title = true

[markup.goldmark.renderer]
unsafe = true

[languages]
  [languages.ja]
    label = "日本語"
    locale = "ja-JP"
    weight = 1

[[languages.ja.menus.main]]
name = "Home"
url = "/"
weight = 1

[[languages.ja.menus.main]]
name = "Research"
url = "/research/"
weight = 10

[[languages.ja.menus.main]]
name = "Publication"
url = "/publication/"
weight = 20

[[languages.ja.menus.main]]
name = "Member"
url = "/member/"
weight = 30

[[languages.ja.menus.main]]
name = "Education"
url = "/education/"
weight = 40

[[languages.ja.menus.main]]
name = "Link"
url = "/link/"
weight = 50

[languages.en]
  label = "English"
  locale = "en-US"
  weight = 2

[[languages.en.menus.main]]
name = "Home"
url = "/en/"
weight = 1

[[languages.en.menus.main]]
name = "Publications"
url = "/en/publication/"
weight = 30

[[languages.en.menus.main]]
name = "Research"
url = "/en/research/"
weight = 10

